version: "3.8" # Specifies the Docker Compose version

services:
  flask-app:
    build: ./backendflask # Path to the Flask app's Dockerfile
    ports:
      - "5000:5000" # Map container port 5000 to local port 5000
    volumes:
      - ./backendflask:/app # Sync local files with the container for live updates
    environment:
      - FLASK_APP=flaskapp.py
      - FLASK_RUN_HOST=0.0.0.0

  frontend-dev:
    build:
      context: ./react-app
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./react-app:/app # Reflect host changes
      - /app/node_modules # Keep container modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling if file‑watch issues
